import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner";
import { envMode, gitSHA } from "@/lib/version";
import { AppBar } from "@/components/layout/top-navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Repo-Purge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <AppBar className="bg-zinc-700 p-2 w-full" />
        {/* Todo main h-full은 top navbar만큼 제외해야 꽉 맞음 */}
        <main className="h-full flex-grow overflow-hidden">{children}</main>
        <footer className="p-4 text-white bg-zinc-950">
          <p>
            © {new Date().getFullYear()} Tinysolver. version: {gitSHA}
          </p>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
